### ISSUE TITLE
Null pointer in System tabs

### ISSUE THREAD

**Issue by Corionis** [Corionis/ELS#120]
New bug when opening the System tabs. Difficult to reproduce but have seen it a couple of time.

ERROR 09/26/2023 15:28:39.905 java.lang.NullPointerException
	at com.corionis.els.gui.browser.Browser.styleComputer(Browser.java:2331)
	at com.corionis.els.gui.browser.Browser.loadSystemTree(Browser.java:1613)
	at com.corionis.els.gui.Navigator$3.actionPerformed(Navigator.java:842)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)

**Comment by Corionis** [comment]
This bug was an artifact of #121 when that was failing.
